config/routes.rb
Amit::Application.routes.draw do
  devise_for :admins, :path_names => { :sign_in => 'login', :sign_out => 'logout'}
  
  devise_scope :admin do 
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end 

  root :to => 'blogs#index', :constraints => lambda {|r| r.env["warden"].authenticate? }

  resources :blogs

  resources :read_blogs
  root :to => "read_blogs#index"
  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  require 'open-uri'
  validates_presence_of :blogger_name
  validates_presence_of :blog_url
  validates_format_of :blog_url, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix
  validates_uniqueness_of :blog_url
  #Associations goes here
  has_many :posts
  
  #This method will read the posts of the blogs and stores it in DB. Currently we are showing the posts directly from the DB.
  def read_posts(blog)
    @doc = Nokogiri::HTML(open("#{blog.blog_url}"))
      if !@doc.nil?
        @doc.css('div.post').each do |node|
          @post = Post.new
          title_url = node.css('h3.post-title a')
          @post.blog_id = blog.id
          blog.blog_title = @doc.css('h1.title').text
          blog.save!
          @post.url = title_url[0]['href']
          @post.title = node.css('h3.post-title').text          
          @post.content = node.css('div.post-body').inner_html.chomp
          @post.author = node.css('span.fn').text          
          published_date = node.css('abbr.published') 
          @post.post_date = Time.parse(published_date[0]['title'].gsub('T'," "))          
          @post.save!
        end         
      end
  end
  
  #This method is used to read posts from pat's blogs
  #We know that separate method for each blog is not a good idea. It's quite difficult to write a generic method since everyone is following different styles for their blogs.
  #Anyway we are trying to figure it out...
  def read_posts_one(blog)
     @doc = Nokogiri::HTML(open("#{blog.blog_url}"))
       if !@doc.nil?
         author_name = @doc.css('title').text
         @doc.css('article.post').each do |node|
           @post = Post.new
           title_url = node.css('h1 a')           
           @post.blog_id = blog.id
           blog.blog_title = "#{author_name}'s blogs"
           blog.save!
           append_url = "http://patshaughnessy.net"
           @post.url = append_url + title_url[0]['href']
           @post.title = node.css('h1').text    
           #content_data = node.css('section.content').inner_html.chomp
           #@post.content = content_data.css('p a').last.attr('href')   
           #links = "http://patshaughnessy.net/" + node.css('section.content').css('a').map{ |link| link['href']}.last           
           content_orig = node.css('section.content').inner_html.chomp
           @post.content = full_content(content_orig,append_url,full_string_content="")     
           @post.author = author_name
           @post.post_date = node.css('span.date').text.to_date
           @post.save!
         end         
       end
  end
  
  #This method is used to read posts from Alex's blogs
   def read_posts_two(blog)
     @doc = Nokogiri::HTML(open("#{blog.blog_url}"))
       if !@doc.nil?   
         author_name = @doc.css('div#header h1').text
         @doc.css('div.post').each do |node|
         @post = Post.new
         title_url = node.css('div.title a')
         @post.blog_id = blog.id
         blog.blog_title = "#{author_name}'s blogs"
         blog.save!
         @post.title = node.css('div.title').text
         @post.post_date = node.css('div.date').text.to_date
         @post.url = "http://www.alexrothenberg.com/" + title_url[0]['href']
         @post.content  = node.css('div.extract').inner_html.chomp         
         @post.author = author_name        
         @post.save!
         end         
       end
  end  

 private
  # This method is used to append the default pat's url to the link which it is missed
  def full_content(content,link,full_string_content="")
    c = content.partition('a href')
    full_string_content << c[0] << c[1]
    if !c[2].empty?
      if c[2].include?('http')
        full_string_content << full_content(c[2],link)
      else
        d = c[2].partition('/')
        g = d[2].partition('>')
        full_string_content << d[0].to_s << link+d[1].to_s + g[0] + " target='_blank'" + g[1] +g[2]
      end
    end
    full_string_content
  end  

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authenticate_admin!
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])  
    respond_to do |format|
      if @blog.save     
        urls1 = [ "http://patshaughnessy.net/","http://patshaughnessy.net"]
        urls2= ["http://www.alexrothenberg.com/", "http://www.alexrothenberg.com"]
       if urls1.include?(@blog.blog_url)      
        @blog.read_posts_one(@blog) 
       elsif urls2.include?(@blog.blog_url)      
         @blog.read_posts_two(@blog)         
       else       
         @blog.read_posts(@blog)        
        end
        format.html { redirect_to @blog, :notice => 'Blog was successfully created.' }
        format.json { render :json => @blog, :status => :created, :location => @blog }
      else
        format.html { render :action => "new" }
        format.json { render :json => @blog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, :notice => 'Blog was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @blog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    Post.delete_all(["id in (?)",@blog.posts.collect(&:id)])
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :blogger_name %><br />
    <%= f.text_field :blogger_name %>
  </div>
  <div class="field">
    <%= f.label :blog_url %>(Please Mention  http:// or https:// )<br />
    <%= f.text_field :blog_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table>
  <tr>
    <th>Blogger name</th>
    <th>Blog url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.blogger_name %></td>
    <td><%= blog.blog_url %></td>
    <td><%= link_to 'Show', blog_path(blog)%></td>
    <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
    <td><%= link_to 'Destroy', blog, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>
<br/>
<%= link_to 'Blog\'s List', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Blogger name:</b>
  <%= @blog.blogger_name %>
</p>

<p>
  <b>Blog url:</b>
  <%= @blog.blog_url %>
</p>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>